Project/mvc4_poject/Models/Post.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace mvc4_poject.Models
{
    public class Post
    {
        public long id { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string IdAuthor { get; set; }
        public string date { get; set; }

        public string intro { get; set; }
        public string body { get; set; }

        public string category { get; set; }
        public string images { get; set; }
        public string video { get; set; }
    }
    public class PostDBContext : DbContext
    {
        public DbSet<Post> Posts { get; set; }
    }
}

Project/mvc4_poject/Controllers/PostController.cs
using mvc4_poject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc4_poject.Controllers
{
    public class PostController : Controller
    {
        private PostDBContext db = new PostDBContext();
        private CommentDBContext db2 = new CommentDBContext();
        private ReporterDBContext dbRep = new ReporterDBContext();

        public ActionResult Index()
        {
            var fullpost = db.Posts.OrderByDescending(post => post.date).ToList();
            var intropost = new List<PostIntro>();
            foreach (var item in fullpost)
            {
                var newitem = new PostIntro();
                char[] delimiterChars = { ',' };
                if (item.images != null)
                {
                    if (item.images.Contains(','))
                        newitem.image = item.images.Split(delimiterChars).First();
                    else
                        newitem.image = item.images;
                }
                else
                {
                    newitem.image = "Images/defualt/news.jpg";
                }
                newitem.id = item.id;
                newitem.title = item.title;
                newitem.category = item.category;
                intropost.Add(newitem);
            }
            return View(intropost);
        }
        /*public ActionResult Index()
        {
            var allPosts = db.Posts;
            var allPostCommets = new List<PostComments>();
            var allComments = from m in db2.Comments
                              select m;
            foreach (var post in allPosts)
            {
                PostComments item = new PostComments();
                item.post = post;
                item.comments = allComments.Where(s => s.postId == post.id);
                item.numberOfCom = item.comments.ToArray<Comment>().Length;
                if (item.numberOfCom == 0)
                {
                    item.comments = null;
                }
                allPostCommets.Add(item);
            }
            var helper = new helperBlogController();
            helper.PostComments = allPostCommets;
            helper.newComment = new Comment();
            return View(helper);
        }*/
        public ActionResult FullPost(int id){
            var allPosts = (from m in db.Posts
                            select m).Where(s => s.id == id);
            var allPostCommets = new List<PostComments>();
            var allComments = from m in db2.Comments
                              select m;
            foreach (var post in allPosts)
            {
                PostComments item = new PostComments();
                item.post = post;
                item.comments = allComments.Where(s => s.postId == post.id);
                item.numberOfCom = item.comments.ToArray<Comment>().Length;
                if (item.numberOfCom == 0)
                {
                    item.comments = null;
                }
                allPostCommets.Add(item);
            }
            var helper = new helperBlogController();
            helper.PostComments = allPostCommets;
            helper.newComment = new Comment();
            return View(helper);
        }

        public ActionResult addComment(int postId, string author, string body, string title)
        {
            Comment c = new Comment();
            c.author = author;
            c.body = body;
            c.postId = postId;
            c.title = title;

            db2.Comments.Add(c);
            db2.SaveChanges();
            return RedirectToAction("FullPost/"+postId);
        }

        public ActionResult AuthorPosts()
        {
            /*doesn't work!!!
             * 1
             * var query =dbRep.Reporter.Join(db.Posts,
                p=>p.ID,
                r=>Convert.ToInt32(r.IdAuthor),
                (p,r)=>new{
                    reporter=p,
                    post=r
                }).ToArray();
            2!!
            var qq=(from s in db.Posts
                   join reporter in dbRep.Reporter on s.IdAuthor equals reporter.ID.ToString()
                   select new{rep=reporter,pos=s}).ToList();
             * 
             * 3!!!
             *  /*var query = (db.Posts).      // source
           Join(dbRep.Reporter,         // target
              c => c.IdAuthor,          // FK-Foreign key
              cm => cm.ID.ToString(),   // PK-Primary key
              (c, cm) => new { AuthorID = cm.ID, AuthorName = cm.name, title = c.title, PostId = c.id }).ToList();  // project result*/
            List<ReporterAndPosts> All = new List<ReporterAndPosts>();
            foreach(var post in db.Posts){
                Reporter rep;
                if(post.IdAuthor=="0"){
                        rep=new Reporter();
                        rep.ID=0;
                        rep.phone="none";
                        rep.email="none";
                        rep.name=post.author;
                }else
                    rep=dbRep.Reporter.Find(Convert.ToInt32(post.IdAuthor));
                var item=new ReporterAndPosts();
                item.rep=rep;
                item.posts=post;
                All.Add(item);
            }

          

            return View(All);
        }

        public ActionResult statistics()
        {
            return View();
        }

        public ActionResult getStatistics()
        {
            List<int> Adata = new List<int>();
            List<string> Anames = new List<string>();
            var a = (from m in db.Posts
                     select m).GroupBy(g => g.category).Select(r => new { Id = r.Key, Count = r.Count() }).ToList();
            foreach (var item in a)
            {
                Adata.Add(item.Count);
                Anames.Add(item.Id);
            }
            return Json(new { names = Anames, Sdata = Adata.ToArray<int>(), len = Anames.ToArray().Length }, JsonRequestBehavior.AllowGet);
        }
    }
}

Project/mvc4_poject/Controllers/ReportersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvc4_poject.Models;

namespace mvc4_poject.Controllers
{
    public class ReportersController : Controller
    {
        private ReporterDBContext db = new ReporterDBContext();
        private PostDBContext db2 = new PostDBContext();

        //
        // GET: /Reporters/

        public ActionResult Index()
        {
            return View(db.Reporter.ToList());
        }

        //
        // GET: /Reporters/Details/5

        public ActionResult Details(long id = 0)
        {
            Reporter reporter = db.Reporter.Find(id);
            if (id == 0)
            {
                return RedirectToAction("Notfounddetails");
            }
            if (reporter == null)
            {
                return HttpNotFound();
            }

                return View(reporter);

        }

        public ActionResult Notfounddetails()
        {

            return View();
        }
        //
        // GET: /Reporters/Create

        public ActionResult Create()
        {
            if (Request.IsAuthenticated)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Denied", "Home");
            }
        }

        //
        // POST: /Reporters/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Reporter reporter)
        {
            if (ModelState.IsValid)
            {
                db.Reporter.Add(reporter);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(reporter);
        }

        //
        // GET: /Reporters/Edit/5

        public ActionResult Edit(long id = 0)
        {
            Reporter reporter = db.Reporter.Find(id);
            if (reporter == null)
            {
                return HttpNotFound();
            }
            if (Request.IsAuthenticated)
            {
                return View(reporter);
            }
            else
            {
                return RedirectToAction("Denied", "Home");
            }

        }

        //
        // POST: /Reporters/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Reporter reporter)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reporter).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(reporter);
        }

        //
        // GET: /Reporters/Delete/5

        public ActionResult Delete(long id = 0)
        {
            Reporter reporter = db.Reporter.Find(id);
            if (reporter == null)
            {
                return HttpNotFound();
            }
            if (Request.IsAuthenticated)
            {
                return View(reporter);
            }
            else
            {
                return RedirectToAction("Denied");
            }
        }

        //
        // POST: /Reporters/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Reporter reporter = db.Reporter.Find(id);
            db.Reporter.Remove(reporter);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult getStatistics()
        {
            List<int> Adata = new List<int>();
            List<string> Anames=new List<string>();
            var a=(from m in db2.Posts
                   select m).GroupBy(g => g.IdAuthor).Select(r => new { Id = r.Key, Count = r.Count() }).ToList();
            foreach (var item in a)
            {
                Adata.Add(item.Count);
                if (db.Reporter.Find(Convert.ToInt32(item.Id)) == null)
                    Anames.Add("Others");
                else
                    Anames.Add(db.Reporter.Find( Convert.ToInt32(item.Id)).name);
            }
            return Json(new { names = Anames, Sdata = Adata.ToArray<int>() ,len=Anames.ToArray().Length}, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Search(string Sname, string Sphone, string Semail)
        {
            var reporters = from m in db.Reporter
                        select m;

            if (!String.IsNullOrEmpty(Sname))
            {
                reporters = reporters.Where(s => s.name.Contains(Sname));
            }

            if (!string.IsNullOrEmpty(Sphone))
            {
                reporters = reporters.Where(x => x.phone.Contains(Sphone));
            }
            if (string.IsNullOrEmpty(Semail))
            {
                return View(reporters);
            }
            else
            {
                return View(reporters.Where(y => y.email.Contains(Semail)));
            }
        }
        public ActionResult GetReportes()
        {
            List<string> names = new List<string>();
            foreach (var item in db.Reporter)
            {
                names.Add(item.name);
            }
            return Json(new { Names = names, len = names.ToArray().Length }, JsonRequestBehavior.AllowGet);
        }
   }
}

Project/mvc4_poject/Views/Post/AuthorPosts.cshtml
@model IEnumerable<mvc4_poject.Models.ReporterAndPosts>

@{
    ViewBag.Title = "AuthorPosts";
}

<h2>AuthorPosts</h2>


<table class="table table-striped" style="border:double">
    <tr>
        <th style="padding-right: 10px; background-color: #4ad06e">id post</th>
        <th style="padding-right: 10px; background-color: #4ad06e">title</th>
        <th style="padding-right: 10px; background-color: #4ad06e">Post date</th>
        <th style="padding-right: 10px; background-color: #4db1ee">id reporter</th>
        <th style="padding-right: 10px; background-color: #4db1ee">name reporter</th>
        <th style="padding-right: 10px; background-color: #4db1ee">phone reporter</th>
        <th style="padding-right: 10px; background-color: #4db1ee">phone reporter</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="background-color: #4ad06e">@item.posts.id</td>
            <td style ="background-color: #4ad06e">@item.posts.title</td>
            <td style="background-color: #4ad06e">@item.posts.date</td>
            <td style="background-color: #4db1ee">@item.rep.ID</td>
            <td style="background-color: #4db1ee">@item.rep.name</td>
            <td style="background-color: #4db1ee">@item.rep.phone</td>
            <td style="background-color: #4db1ee">@item.rep.email</td>
      </tr>
    }

</table>

<h1 style="background-color: #4db1ee">all the data with this background got from Reporters database</h1>
<h1 style="background-color: #4ad06e; ">all the data with this background got from Posts database</h1>

<a href="/Post/index" class="btn btn-primary" role="button" style="">Return</a> 

Project/mvc4_poject/Views/Post/FullPost.cshtml
@model mvc4_poject.Models.helperBlogController

@{
    ViewBag.Title = Model.PostComments.First().post.title;
 }
<link href='http://fonts.googleapis.com/css?family=Montserrat:700' rel='stylesheet' type='text/css'>
<!--always will be one-->
@foreach (var item in Model.PostComments)
{
    <div style="width:100%">
        <section style="padding:12px">
            <article class=" blogpost" style="width:100%" >
                <header>
                    <b2>@item.post.title</b2>
                    <p>
                        <h2 style="font-family: BarFont;">
                            Posted on (@item.post.date)
                            <br />Written by
                            <a href=@Url.Action("Details", "Reporters", new { id = item.post.IdAuthor })>@item.post.author</a><br />
                                Category: @item.post.category <br />
                                Number of comments: @(item.numberOfCom)
                        </h2>
                    </p>
                </header>
                <p>
                    <h5 style="font-size: medium">@item.post.intro</h5>
                </p>
                
                    <div>
                        <h2>@item.post.body</h2><br />
                        @if (@item.post.images != null)
                        {
                            char[] delimiterChars = { ',' };
                            string[] images = (item.post.images.Split(delimiterChars));

                                <div id="myCarousel" class="carousel slide" data-ride="carousel">
                                    <!-- Indicators -->
                                    <ol class="carousel-indicators">
                                        <!--
                               <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                            -->
                                        @{int counter = 0;}
                                        <li data-target="#myCarousel" data-slide-to=@counter class="active"></li>
                                        @{counter = counter + 1;}
                                        @for (var i = 1; i < images.Count(); i++, counter++)
                                        {
                                            <li data-target="#myCarousel" data-slide-to=@counter></li>
                                        }
                                    </ol>

                                    <!-- Wrapper for slides -->
                                    <div class="carousel-inner" role="listbox">
                                        @{counter = 2;}
                                        @foreach (var helper2 in images)
                                        {
                                            if (counter.Equals(2))
                                            {
                                                <div class="item active" align="center">
                                                    <img src=@helper2 alt="" width="700" height="700" align="middle">
                                                    <div class="carousel-caption">
                                                    </div>
                                                </div>
                                                        counter = 3;
                                            }
                                            else
                                            {
                                                <div class="item" align="center">
                                                    <img src=@helper2 alt="" width="700" height="700" align="middle">
                                                    <div class="carousel-caption">
                                                    </div>
                                                </div>
                                            }

                                        }
                                    </div>

                                    <!-- Left and right controls -->
                                    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                </div>



                        }

                        @if (@item.post.video != null)
                        {
                            <video controls="controls" style="padding-top:15px">
                                <source src=@item.post.video type="video/mp4" />
                                Your browser does not support the video tag.
                            </video>
                        }

                    </div>
</article>
        </section>
    </div>
    
    if (item.comments != null)
    {
        <article id="headline">
            <h2 style="text-decoration: underline;">comments:</h2><br />
        </article>
        foreach (var comment in item.comments)
        {
                <!--all the comments-->
                <article id="headline" style="padding-left:8px" >
                        <h3 style="text-decoration: underline">@comment.title</h3>
                        by: @comment.author<br />
                        @comment.body
                </article>
        }
    }    <br />
        <div>
            <article>
                <form action="/Post/addComment">
                    <h2>Add new comment:</h2>
                    <h3>
                        <input type="text" class="form-control" id="author" name="author" maxlength="25" placeholder="Author" style="width:300px;" />
                        <input type="text" class="form-control" id="title" name="title" maxlength="25" placeholder="Title" style="width:300px;" />
                        <input type="text" class="form-control" id="body" name="body" placeholder="Comment.." style="width:300px;" />
                    </h3>
                    <input type="text" name="postId" value="@item.post.id" readonly hidden><br>
                    <input type="submit" class="btn btn-primary btn-default" role="button" value="Submit" /><br />
                </form>
            </article>
        </div>

}

Project/mvc4_poject/Views/Post/Index.cshtml
@model IEnumerable<mvc4_poject.Models.PostIntro>

@{
    ViewBag.Title = "Index";
}

<div id="search">
    <h2 style="padding-bottom:10px">Sort by category:</h2>
    <span class="category_buttons" data-categry="All">
        <button type="button" class="btn btn-default">All</button>
    </span>

    <span class="category_buttons" data-categry="Politics">
        <button type="button" class="btn btn-primary">Politics</button>
    </span>

    <!-- Indicates a successful or positive action -->
    <span class="category_buttons" data-categry="Economy">
        <button type="button" class="btn btn-success">Economy</button>
    </span>

    <!-- Contextual button for informational alert messages -->
    <span class="category_buttons" data-categry="Sports">
        <button type="button" class="btn btn-info">Sports</button>
    </span>

    <!-- Indicates caution should be taken with this action -->
    <span class="category_buttons" data-categry="Celebrity">
        <button type="button" class="btn btn-warning">Celebrity</button>
    </span>

    <!-- Indicates a dangerous or potentially negative action -->
    <span class="category_buttons" data-categry="Technology">
        <button type="button" class="btn btn-danger">Technology</button>
    </span>

    <span class="category_buttons" data-categry="Other">
        <button type="button" class="btn btn-default">Other</button>
    </span>
    <a href="/Post/statistics" class="btn btn-primary" role="button" style="float:right">Show statistics</a> 
    <a href="/Post/AuthorPosts" class="btn btn-primary" role="button" style="float:right">All posts in table</a> 
</div>

@foreach (var item in Model)
{
    <div class="row" style="float: left; width: 50%;height:550px" data-categry="@item.category">
        <div class="col-sm-6 col-md-4" style="width: 100%; max-height: 550px">
            <div class="thumbnail" style="max-height:550px">
                <img src="@item.image" class="imageS" alt="" style="max-height:400px"><s5>@item.title</s5>
                <div class="caption" style="max-height:150px">
                    <h2 id="intro-@item.id"></h2>
                </div>
                <p><span class="intro" data-idpost="@item.id"><a class="btn btn-default" role="button" id="introButton">Intro</a></span> <a href="/Post/FullPost/@item.id" class="btn btn-primary" role="button">Full Article</a></p>
            </div>
        </div>
    </div>
}

@section scripts {

    <script type="text/javascript">

        $(document).ready(function () {
            $(".intro").mousedown(function () {
                var Id1 = $(this).attr("data-idpost");
                $.ajax({
                    url: '@Url.Action("GetIntro", "Home")',
                    type: 'GET',
                    dataType: 'json',

                    cache: false,
                    data: { Postid: Id1 },
                    success: function (data) {
                        var x = data;
                        document.getElementById("intro-" + Id1).innerHTML = data.intro;
                    }
                });

            })
        });
    </script>

    <script type="text/javascript">

        $(document).ready(function () {
            $(".category_buttons").mousedown(function () {
                var c = $(this).attr("data-categry");
                $(".row").each(function (item) {
                    if (c == "All") {
                        $(this).show();
                    }
                    else {
                        if ($(this).data("categry") != c) {
                            $(this).hide();
                        } else {
                            $(this).show();
                        }
                    }
                });
                
            })
        });
    </script>


}

Project/mvc4_poject/Views/Post/statistics.cshtml
@{
    ViewBag.Title = "statistics";
}
<br />
<br />
<h1 style="text-decoration: underline;"><b>Post statistics:</b></h1>




<h3>Posts of each category:</h3>
<style>
    .chart rect {
        fill: steelblue;
    }

    .chart text {
        font: 10px sans-serif;
    }

    .axis path {
        display: none;
    }

    .axis line {
        stroke: #fff;
        stroke-opacity: .5;
        shape-rendering: crispEdges;
    }
</style>

<div style="float:left;font-size:small">
    <div id="names" style="padding-top:30px">
        <!--aaa<br />
        aaa<br />
        aaa<br />
        aaa<br />-->
    </div>
</div>
<div style="">
    <svg class="chart"></svg>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"></script>

    <script>
    var Sdata = null;
    var Ndata = null;
    $.ajax({
        url: '@Url.Action("getStatistics", "Post")',
        type: 'GET',
        dataType: 'json',

        cache: false,
        data: {  },
        success: function (data) {
            Sdata = data.Sdata;
            Ndata = data.names;
            for(i=0;i<data.len;i++){
                document.getElementById("names").innerHTML += Ndata[i] + "<br />";
            }
            var data = Sdata;
            var margin = { top: 30, right: 0, bottom: 0, left: 30 },
                width = 420,
                barHeight = 20,
                height = barHeight * data.length;

            var x = d3.scale.linear()
                .domain([0, d3.max(data)])
                .range([0, width]);

            var xAxis = d3.svg.axis()
                .scale(x)
                .orient("top")
                .tickSize(-height);

            var chart = d3.select(".chart")
                .attr("width", width + margin.left + margin.right)
                .attr("height", height + margin.top + margin.bottom)
              .append("g")
                .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

            chart.append("g")
                .attr("class", "bars")
              .selectAll("rect")
                .data(data)
              .enter().append("rect")
                .attr("y", function (d, i) { return i * barHeight; })
                .attr("height", barHeight - 1)
                .attr("width", x);

            chart.append("g")
                .attr("class", "axis")
                .call(xAxis)
              .select(".tick line")
                .style("stroke", "#000");

        }
    });

    </script>
</div>
<a href="/Post/index" class="btn btn-primary" role="button" style="">Return</a> 