Project/mvc4_poject/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvc4_poject.Models;

namespace mvc4_poject.Controllers
{
    public class ManagerController : Controller
    {
        private PostDBContext db = new PostDBContext();
        private CommentDBContext db2 = new CommentDBContext();
        private ReporterDBContext dbReporter = new ReporterDBContext();

        //
        // GET: /Post/

        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                return View(db.Posts.ToList());
            }
            else
            {
                return RedirectToAction("Denied", "Home");
            }
        }

        //
        // GET: /Post/Details/5

        public ActionResult Details(long id = 0)
        {
            if (Request.IsAuthenticated)
            {
                Post post = db.Posts.Find(id);

                if (post == null)
                {
                    return HttpNotFound();
                }
                return View(post);
            }
             else
            {
                return RedirectToAction("Denied", "Home");
            }
        }

        //
        // GET: /Post/Create

        public ActionResult Create()
        {
            if (Request.IsAuthenticated)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Denied", "Home");
            }
        }

        //
        // POST: /Post/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Post post)
        {
            if (Request.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    var rep = (from m in dbReporter.Reporter
                               where m.name == post.author
                               select m);
                    if (rep.ToArray<Reporter>().Length == 0)
                    {
                        post.IdAuthor = "0";
                    }
                    else
                    {
                        post.IdAuthor = "" + rep.First<Reporter>().ID;
                    }

                    post.date = DateTime.Now.ToString();
                    db.Posts.Add(post);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(post);
            }
            else
            {
                return RedirectToAction("Denied", "Home");
            }
        }


        //
        // GET: /Post/Edit/5

        public ActionResult Edit(long id = 0)
        {
            if (Request.IsAuthenticated)
            {
                Post post = db.Posts.Find(id);
                if (post == null)
                {
                    return HttpNotFound();
                }
                return View(post);
            }
            else
            {
                return RedirectToAction("Denied", "Home");
            }
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Post post)
        {
            if (Request.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(post).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(post);
            }
            else
            {
                return RedirectToAction("Denied", "Home");
            }
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(long id = 0)
        {
            if (Request.IsAuthenticated)
            {
                Post post = db.Posts.Find(id);
                if (post == null)
                {
                    return HttpNotFound();
                }
                return View(post);
            }
            else
            {
                return RedirectToAction("Denied", "Home");
            }
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            if (Request.IsAuthenticated)
            {
                Post post = db.Posts.Find(id);
                db.Posts.Remove(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Denied", "Home");
            }
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        //comments
        public ActionResult Comments(long id = 0)
        {
            if (Request.IsAuthenticated)
            {
                Console.WriteLine("id:" + id);
                Post post = db.Posts.Find(id);
                if (post == null)
                {
                    return HttpNotFound();
                }
                var allComments = from m in db2.Comments
                                  select m;

                allComments = allComments.Where(s => s.postId == id);
                if (allComments == null)
                    return HttpNotFound();
                return View(allComments);
            }
            else
            {
                return RedirectToAction("Denied", "Home");
            }
        }

        public ActionResult DeleteComment(long PostId = 0, long CommentId = 0)
        {
            if (Request.IsAuthenticated)
            {
                Comment com = db2.Comments.Find(CommentId);
                if (com == null)
                {
                    return HttpNotFound();
                }
                db2.Comments.Remove(com);
                db2.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Denied", "Home");
            }
        }

        public ActionResult Getdetails(int Postid)
        {
            var mypost = (from e in db.Posts
                          where e.id == Postid
                          select e).First();
            return Json(new { intro = mypost.intro, author = mypost.author, category=mypost.category ,date=mypost.date}, JsonRequestBehavior.AllowGet);
        }
    }
}

Project/mvc4_poject/Controllers/PostController.cs
using mvc4_poject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc4_poject.Controllers
{
    public class PostController : Controller
    {
        private PostDBContext db = new PostDBContext();
        private CommentDBContext db2 = new CommentDBContext();
        private ReporterDBContext dbRep = new ReporterDBContext();

        public ActionResult Index()
        {
            var fullpost = db.Posts.OrderByDescending(post => post.date).ToList();
            var intropost = new List<PostIntro>();
            foreach (var item in fullpost)
            {
                var newitem = new PostIntro();
                char[] delimiterChars = { ',' };
                if (item.images != null)
                {
                    if (item.images.Contains(','))
                        newitem.image = item.images.Split(delimiterChars).First();
                    else
                        newitem.image = item.images;
                }
                else
                {
                    newitem.image = "Images/defualt/news.jpg";
                }
                newitem.id = item.id;
                newitem.title = item.title;
                newitem.category = item.category;
                intropost.Add(newitem);
            }
            return View(intropost);
        }
        /*public ActionResult Index()
        {
            var allPosts = db.Posts;
            var allPostCommets = new List<PostComments>();
            var allComments = from m in db2.Comments
                              select m;
            foreach (var post in allPosts)
            {
                PostComments item = new PostComments();
                item.post = post;
                item.comments = allComments.Where(s => s.postId == post.id);
                item.numberOfCom = item.comments.ToArray<Comment>().Length;
                if (item.numberOfCom == 0)
                {
                    item.comments = null;
                }
                allPostCommets.Add(item);
            }
            var helper = new helperBlogController();
            helper.PostComments = allPostCommets;
            helper.newComment = new Comment();
            return View(helper);
        }*/
        public ActionResult FullPost(int id){
            var allPosts = (from m in db.Posts
                            select m).Where(s => s.id == id);
            var allPostCommets = new List<PostComments>();
            var allComments = from m in db2.Comments
                              select m;
            foreach (var post in allPosts)
            {
                PostComments item = new PostComments();
                item.post = post;
                item.comments = allComments.Where(s => s.postId == post.id);
                item.numberOfCom = item.comments.ToArray<Comment>().Length;
                if (item.numberOfCom == 0)
                {
                    item.comments = null;
                }
                allPostCommets.Add(item);
            }
            var helper = new helperBlogController();
            helper.PostComments = allPostCommets;
            helper.newComment = new Comment();
            return View(helper);
        }

        public ActionResult addComment(int postId, string author, string body, string title)
        {
            Comment c = new Comment();
            c.author = author;
            c.body = body;
            c.postId = postId;
            c.title = title;

            db2.Comments.Add(c);
            db2.SaveChanges();
            return RedirectToAction("FullPost/"+postId);
        }

        public ActionResult AuthorPosts()
        {
            /*doesn't work!!!
             * 1
             * var query =dbRep.Reporter.Join(db.Posts,
                p=>p.ID,
                r=>Convert.ToInt32(r.IdAuthor),
                (p,r)=>new{
                    reporter=p,
                    post=r
                }).ToArray();
            2!!
            var qq=(from s in db.Posts
                   join reporter in dbRep.Reporter on s.IdAuthor equals reporter.ID.ToString()
                   select new{rep=reporter,pos=s}).ToList();
             * 
             * 3!!!
             *  /*var query = (db.Posts).      // source
           Join(dbRep.Reporter,         // target
              c => c.IdAuthor,          // FK-Foreign key
              cm => cm.ID.ToString(),   // PK-Primary key
              (c, cm) => new { AuthorID = cm.ID, AuthorName = cm.name, title = c.title, PostId = c.id }).ToList();  // project result*/
            List<ReporterAndPosts> All = new List<ReporterAndPosts>();
            foreach(var post in db.Posts){
                Reporter rep;
                if(post.IdAuthor=="0"){
                        rep=new Reporter();
                        rep.ID=0;
                        rep.phone="none";
                        rep.email="none";
                        rep.name=post.author;
                }else
                    rep=dbRep.Reporter.Find(Convert.ToInt32(post.IdAuthor));
                var item=new ReporterAndPosts();
                item.rep=rep;
                item.posts=post;
                All.Add(item);
            }

          

            return View(All);
        }

        public ActionResult statistics()
        {
            return View();
        }

        public ActionResult getStatistics()
        {
            List<int> Adata = new List<int>();
            List<string> Anames = new List<string>();
            var a = (from m in db.Posts
                     select m).GroupBy(g => g.category).Select(r => new { Id = r.Key, Count = r.Count() }).ToList();
            foreach (var item in a)
            {
                Adata.Add(item.Count);
                Anames.Add(item.Id);
            }
            return Json(new { names = Anames, Sdata = Adata.ToArray<int>(), len = Anames.ToArray().Length }, JsonRequestBehavior.AllowGet);
        }
    }
}

Project/mvc4_poject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - S&B News</title>
    <link href="~/sbicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <link href='http://fonts.googleapis.com/css?family=Montserrat:700' rel='stylesheet' type='text/css'>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div>
        <nav class="navbar navbar-inverse" style="position: absolute;left: 0;width: 100%;">
            <ul class="nav navbar-nav">
                <li style=" font-size: 2.5em;">@Html.ActionLink("Home", "Index", "Home")</li>
                <li style=" font-size: 2.5em;">@Html.ActionLink("All posts", "Index", "Post")</li>
                @if (Request.IsAuthenticated)
                {
                    <li style=" font-size: 2.5em;">@Html.ActionLink("Reporters(Admin)", "Index", "Reporters")</li>
                }
                else
                {
                    <li style=" font-size: 2.5em;">@Html.ActionLink("Reporters", "Index", "Reporters")</li>
                }
                <li style=" font-size: 2.5em;">@Html.ActionLink("Weather", "Weather", "Home")</li>
                @if (Request.IsAuthenticated)
                {
                    <li style=" font-size: 2.5em;">@Html.ActionLink("Admin(" + User.Identity.Name+")", "Index", "Manager")</li>
                }
                else
                {
                    <li style=" font-size: 2.5em;">@Html.ActionLink("Admin Login", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                }
                
            </ul>
        </nav>
        <div style="left:0; height: 170px; width: 100%; ">
            <img src="/Images/defualt/title.png" style="height: 100%;width:100%;margin-top:45px;margin-left:auto;margin-right:auto" />
        </div>
    </div>

    <div id="body">
        
        @RenderSection("featured", required: false)
        <div style="padding-left: 25px ">
            @RenderBody()
        </div>
    </div>
    <footer>
            <div class="float-left">
                <h3>Date:@DateTime.Now</h3>
                <h3>&copy; Made by:Bar Magnezi & Senia kalma</h3>
            </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>